DROP DATABASE IF EXISTS `RESTAURANT`;
create DATABASE RESTAURANT;
use RESTAURANT;

DROP TABLE IF EXISTS `EMPLOYEES`;
DROP TABLE IF EXISTS `EMPLOYEE_DEPENDENTS`;
DROP TABLE IF EXISTS `ORDER`;
DROP TABLE IF EXISTS `MENU`;
DROP TABLE IF EXISTS `ORDER_ITEM`;
DROP TABLE IF EXISTS `CHEF`;
DROP TABLE IF EXISTS `PAYMENT`;
DROP TABLE IF EXISTS `TABLE`;
DROP TABLE IF EXISTS `IS_SERVING`;
DROP TABLE IF EXISTS `WAITER`;
DROP TABLE IF EXISTS `FOOD IDS`;
DROP TABLE IF EXISTS `CUSTOMER`;

CREATE TABLE `EMPLOYEES`(
	EMPLOYEE_ID INT NOT NULL,
	FIRST_NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30),
	CONTACT_NUMBER VARCHAR(10) NOT NULL,
	SALARY INT,
	PRIMARY KEY(`EMPLOYEE_ID`)
);

CREATE TABLE `EMPLOYEE_DEPENDENTS`(
	EMPLOYEE_ID INT NOT NULL,
	FIRST_NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30),
	FOREIGN KEY(`EMPLOYEE_ID`) REFERENCES `EMPLOYEES`(`EMPLOYEE_ID`)	
);

CREATE TABLE `TABLE`(
	TABLE_ID INT NOT NULL,
	CUSTOMER_ID INT,
	ORDER_ID INT,
	PRIMARY KEY(`TABLE_ID`)
);

CREATE TABLE `CUSTOMER`(
	CUSTOMER_ID INT NOT NULL,
	FIRST_NAME VARCHAR(30) NOT NULL,
	LAST_NAME VARCHAR(30),
	PAYMENT_ID INT NOT NULL,
	ORDER_ID INT NOT NULL,
	PRIMARY KEY(`CUSTOMER_ID`)
);

CREATE TABLE `ORDER`(
	ORDER_ID INT NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	ORDER_DATE DATE NOT NULL,
	STATUS VARCHAR(20) NOT NULL,
	PAYMENT_ID INT NOT NULL,
	PRIMARY KEY(`ORDER_ID`),
	FOREIGN KEY(`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_ID`)
);

CREATE TABLE `PAYMENT`(
	PAYMENT_ID INT NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	ORDER_ID INT NOT NULL,
	AMOUNT INT NOT NULL,
	PAYMENT_TYPE VARCHAR(30) NOT NULL,
	PAYMENT_DATE DATE NOT NULL,
	STATUS VARCHAR(30) NOT NULL,
	PRIMARY KEY(`PAYMENT_ID`),
	FOREIGN KEY(`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`),
	FOREIGN KEY(`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_ID`)
);

CREATE TABLE `MENU`(
	FOOD_ID INT NOT NULL,
	FOOD_ITEM VARCHAR(30) NOT NULL,
	PRICE INT NOT NULL,
	PRIMARY KEY(`FOOD_ID`)
);

CREATE TABLE `CHEF`(
	EMPLOYEE_ID INT NOT NULL,
	ORDER_ID INT,
	PRIMARY KEY(`EMPLOYEE_ID`)
);

CREATE TABLE `ORDER_ITEM`(
	ORDER_ID INT NOT NULL,
	FOOD_ID INT NOT NULL,
	QUANTITY INT NOT NULL,
	ORDER_DATE DATE NOT NULL,
	UNIT_PRICE INT NOT NULL,
	CHEF_ID INT NOT NULL,
	STATUS VARCHAR(20) NOT NULL,
	FOREIGN KEY(`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`),
	FOREIGN KEY(`FOOD_ID`) REFERENCES `MENU`(`FOOD_ID`),
	FOREIGN KEY(`CHEF_ID`) REFERENCES `CHEF`(`EMPLOYEE_ID`)
);

CREATE TABLE `WAITER`(
	EMPLOYEE_ID INT NOT NULL,
	CUSTOMER_ID INT,
	ORDER_ID INT,
	TABLE_ID INT,	
	PRIMARY KEY(`EMPLOYEE_ID`)
);

CREATE TABLE `IS_SERVING`(
	EMPLOYEE_ID INT NOT NULL,
	TABLE_ID INT NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	FOREIGN KEY(`EMPLOYEE_ID`) REFERENCES `WAITER`(`EMPLOYEE_ID`),
	FOREIGN KEY(`CUSTOMER_ID`) REFERENCES `CUSTOMER`(`CUSTOMER_ID`),
	FOREIGN KEY(`TABLE_ID`) REFERENCES `TABLE`(`TABLE_ID`)
);

CREATE TABLE `FOOD_IDS`(
	FOOD_ID INT NOT NULL,
	ORDER_ID INT NOT NULL,
	FOREIGN KEY(`ORDER_ID`) REFERENCES `ORDER`(`ORDER_ID`),
	PRIMARY KEY(`FOOD_ID`,`ORDER_ID`)
);